# Generated by Django 5.0.7 on 2024-08-26 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolmanagement_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='repository_path',
            field=models.TextField(),
        ),
    ]
