# Generated by Django 5.0.7 on 2024-08-26 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemMonitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_number', models.CharField(max_length=255)),
                ('user', models.CharField(max_length=255)),
                ('processid', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=255)),
                ('software', models.CharField(max_length=255)),
                ('open_time', models.CharField(blank=True, max_length=255, null=True)),
                ('close_time', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
